# Generated by Django 3.1.2 on 2020-10-23 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('otzpaywall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='ofile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='url',
            name='pfile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
